// <auto-generated />
using System;
using EFCore_Exa2.Applications.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EFCore_Exam3.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFCore_Exa2.Applications.Entities.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CreateDate");

                    b.Property<string>("Scores")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Scores");

                    b.Property<int>("StudentId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("StudentId");

                    b.Property<int>("SubjectId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SubjectId");

                    b.HasKey("Id")
                        .HasName("PK_MarkId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("tbl_mark", (string)null);
                });

            modelBuilder.Entity("EFCore_Exa2.Applications.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("StudentId");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("Birthday");

                    b.Property<int>("Gender")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("StudentName");

                    b.Property<bool>("Status")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("Status");

                    b.HasKey("Id")
                        .HasName("PK_StudentId");

                    b.ToTable("tbl_student", (string)null);
                });

            modelBuilder.Entity("EFCore_Exa2.Applications.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SubjectId");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SubjectName");

                    b.Property<bool>("Status")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("Status");

                    b.HasKey("Id")
                        .HasName("PK_SubjectId");

                    b.ToTable("tbl_subject", (string)null);
                });

            modelBuilder.Entity("EFCore_Exa2.Applications.Entities.Mark", b =>
                {
                    b.HasOne("EFCore_Exa2.Applications.Entities.Student", "StudentNavigation")
                        .WithMany("Marks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Student_Mark");

                    b.HasOne("EFCore_Exa2.Applications.Entities.Subject", "SubjectNavigation")
                        .WithMany("Marks")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Subject_Mark");

                    b.Navigation("StudentNavigation");

                    b.Navigation("SubjectNavigation");
                });

            modelBuilder.Entity("EFCore_Exa2.Applications.Entities.Student", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("EFCore_Exa2.Applications.Entities.Subject", b =>
                {
                    b.Navigation("Marks");
                });
#pragma warning restore 612, 618
        }
    }
}
